### PR TITLE
Update to Xcode 10.2 and Swift 5.0

### PR DESCRIPTION
**Pull request by taher-mosbah**
Run the migration assistant on framework and test apps, tests are green and 0 warnings.

### CODE REVIEW

**Comment by taher-mosbah** [comment]
Will update CI script as soon as Xcode 10.2 is available.

**Comment by k0nserv** [comment]
Thanks a bunch @taher-mosbah

**Comment by k0nserv** [comment]
Hey @taher-mosbah CI still seems to have issues here. Do you want to continue looking at it or should I pick it up?

**Comment by taher-mosbah** [comment]
Hey @k0nserv I won't have much time coming days, feel free to pick it up, really sorry for that.

**Comment by dejanskledar** [comment]
Any updates on this?

**Comment by adamszeptycki** [comment]
Any plans to merge it?

**Comment by k0nserv** [comment]
Hey, I don't have time to work on this, but I am happy to merge it if someone can create a PR that passes CI, specifically that still works for Swift 3.1 which seems broken in this PR

**Comment by k0nserv** [comment]
I've released version 3.7.0 which specifies the `swift_versions` attribute in the podspec. This should mean that you can use `SkyFloatingLabelTextField` in your Swift 5 projects before someone gets the time to look at and finish this PR

**Comment by k0nserv** [comment]
Closed in favour of #290

**Pull request closed without merging**
