### PR TITLE
Allow title label font to be set

### PR DESCRIPTION
**Pull request by ryanwaggoner**

### CODE REVIEW

**Comment by intonarumori** [comment]
Hey @ryanwaggoner , thanks for taking the time to contribute.

I'm afraid we cannot accept the PR in the current form.
If you look at the `files changed` tab it's evident that you have switched to space based tabbing.

Would you mind fixing this issue?

**Comment by ryanwaggoner** [comment]
Fixed

**Comment by intonarumori** [comment]
@ryanwaggoner  Thanks.

One more thing, let's use `titleFont` in `createTitleLabel` like we do with `titleColor`.

**Comment by ryanwaggoner** [comment]
Ah yeah, I had that originally, and missed it when going back to spaces. One min.

**Comment by ryanwaggoner** [comment]
Done

**Comment by intonarumori** [comment]
@ryanwaggoner  Thanks.

Do you think we could get rid of the change in the project file? It seems you just disabled tab based white spacing for that one file.
It would be nice to get that removed and really just have the changes in the `SkyFloatingLabelTextField` class.

**Comment by intonarumori** [comment]
@ryanwaggoner Great, many thanks.

I have to double check what happens if you change the `titleFont` to a smaller or larger one, and how the title label font height might affect the placement of other view components.

This might take a while so I will get back to you with my review and hopefully PR approval.

**Comment by intonarumori** [comment]
@ryanwaggoner 
I've been looking at our test cases and just realised that you can set the title font already by using `textField.titleLabel.font = yourCustomFont`. Maybe that solves your current use cases and you can use it straight away.

I have to do some more investigations to determine if leaving `titleLabel` exposed or adding the `titleFont` property is a better choice in the long term. I get back to this PR with my findings.

**Comment by Fawxy** [comment]
It's nice having it as an `@IBInspectable`

**Comment by k0nserv** [comment]
Closing as #141 was merged

**Pull request closed without merging**
