### PR TITLE
Migrate to Swift 3

### PR DESCRIPTION
**Pull request by DenHeadless**
Hey! 

Since we need this framework working for our app, we wanted to help with migration to Swift 3.

What's in this PR?
- [x] Migrated SkyFloatingLabelTextField framework and unit test target to Swift 3 syntax
- [x] Migrated example target to Swift 3
- [x] Verified that all unit tests pass
- [x] Verified that example app functions properly
- [x] Switched to Xcode 8 for running tests on Travis CI
- [x] Added .swift-version file to allow properly linting podspec when you are ready to release

I did not do any Swift API design guidelines-related changes, i thought that as library authors, you would probably want to make those choices yourselves. I would be happy to help with other issues of Swift 3 transition, if they arise.

Thanks for awesome library, and hope this PR will be helpful.

### CODE REVIEW

**Comment by Tibb** [comment]
Hi @DenHeadless, could you consider putting your pull request on a public repo? Then we'll be able to integrate it with cocoapods and use it a temporary solution at least. Thanks a lot!

**Comment by DenHeadless** [comment]
@Tibb What do you mean by public repo? It is public, we are using it in CocoaPods, like so:

```ruby
pod 'SkyFloatingLabelTextField', git: "https://github.com/MLSDev/SkyFloatingLabelTextField.git", branch: "swift3"
```

**Comment by Tibb** [comment]
@DenHeadless Well, I might have made a mistake in the path in my podfile when I tried to use your branch... :/ Thanks for the tip, seems to work 👍

**Comment by DenHeadless** [comment]
@gergelyorosz @intonarumori Guys, just pinging you in case you haven't seen this PR. I understand that's an open-source, and you don't owe us anything, but any hint on when this could be merged or not merged would be nice, since already 20 days have passed since PR was opened.

As i've said, we'll be happy to help if any other assistance is needed with Swift 3 migration.

**Comment by wolffan** [comment]
@DenHeadless  Hello! Thanks for this. I haven't had time to look at this.
My plan is though: migrate first the 2.3 PR -> https://github.com/Skyscanner/SkyFloatingLabelTextField/pull/69

Then do a major version changes for this one.

Not sure I'll have time to do both today. But It's going to happen.
Thanks for your work and patience

**Comment by DenHeadless** [comment]
@wolffan Thanks! No worries, take your time! 🍺

**Comment by chungbd** [comment]
I've just used this lib for my application, so I really so interested in updating code to Swift 3.0.

@wolffan  you met an obstacle, didn't you? Let's know it, may everybody can help you. Thanks

**Comment by ctews** [comment]
+1

**Comment by intonarumori** [comment]
+1

**Comment by k0nserv** [comment]
Hey @DenHeadless can you rebase this on master?

**Comment by DenHeadless** [comment]
@k0nserv Sure, rebased.

**Comment by DenHeadless** [comment]
Travis failure seems completely unrelated to code changes in PR. Tests pass locally on my machine. iOS CI as always, incredibly stable =)

**Comment by k0nserv** [comment]
I'll run them locally too, restarted travis as well. Might be a fluke

**Comment by k0nserv** [comment]
Right tests, pass locally for me as well

**Comment by k0nserv** [comment]
@bogren might have fixed the travis issue in #76 if you wanna try and rebase again

**Comment by DenHeadless** [comment]
Sure, let's give it a shot =) Rebased once more.

**Comment by k0nserv** [comment]
That did it, thanks @bogren 👍  Just gotta finish up the work on 2.3 then we can merge this

**Comment by bogren** [comment]
Awesome! 👏  No problem ☺️

**Comment by wolffan** [comment]
Merged 2.3!
Can we resolve conflicts :) ?

**Comment by DenHeadless** [comment]
Rebased once more =)

**Comment by k0nserv** [comment]
Great thank you for all the help @DenHeadless

**Comment by bogren** [comment]
Sorry, you have to rebase again 😇

**Comment by k0nserv** [comment]
We can always rebase ourselves, no need to do it

**Comment by DenHeadless** [comment]
Yep, edits from maintainers is on =) Please just let me know when you are ready to merge, and i can rebase one final time =)

**Comment by k0nserv** [comment]
Massive thanks for this PR @DenHeadless :)

**Comment by DenHeadless** [comment]
Thank you guys! This is great news! Are you planning 2.0 release for CocoaPods?

**Comment by k0nserv** [comment]
Yeah, I'm working on that at the moment

**Comment by k0nserv** [comment]
See #81

**Pull request merged**
