### PR TITLE
Added suggestion and Added Title to not uppercase only

### PR DESCRIPTION
**Pull request by trr-amsiq**

### CODE REVIEW

**Comment by k0nserv** [comment]
This seems to contain a lot more than what you've stated in the PR title/description please only include the revelant changes to the `README.md`

**Comment by trr-amsiq** [comment]
The title is correct just a bunch of fixes

**Comment by k0nserv** [comment]
I don't understand? From the title I only expect usage instructions for disabling upper casing to be in the PR. However I see a bunch of other stuff including a whole new class `SearchTextField`

**Comment by trr-amsiq** [comment]
Yes it is suggestions

**Comment by k0nserv** [comment]
Suggestions feels outside the scope of this project. I don't think I will merge these changes. Instead I'd suggest you make it a generic extension that can work with any `UITextField` or subclass thus making it possible to use alongside `SkyFloatingLabelTextField`. Alternatively use it from your fork.

Sorry

**Comment by trr-amsiq** [comment]
Can you delete PR than?

**Pull request closed without merging**
