### PR TITLE
Custom Error Colors for Line, Title, Text

### PR DESCRIPTION
**Pull request by InbarSletean**
This PR adds the customization for the for underline, textfield text and title text colors, when error message is set.

### CODE REVIEW

**Comment by k0nserv** [comment]
Hey @InbarSletean this looks pretty good generally. Could you add an entry to `CHANGELOG.md` under the master section and possibly squash the commits? If you are not comfortable with squashing I can do it instead

**Comment by InbarSletean** [comment]
@k0nserv I've added the changes to the `CHANGELOG.md` .
I'd be glad if you could squash the commits

**Comment by k0nserv** [comment]
I've cherry picked the commit and will merge it in #208

**Comment by k0nserv** [comment]
Released in 3.5.0

**Pull request closed without merging**
