### PR TITLE
Added Validator.

### PR DESCRIPTION
**Pull request by Matic1993**
Added some default validation.

User can also add custom regex for validation.

### CODE REVIEW

**Comment by k0nserv** [comment]
Hey @Matic1993,

I think this should be more general. Instead of having a single protocol with many checks it should be a protocol with a single unified interface.

```swift
typealias Valdiator = (text: String) -> (Bool, String)?
```

and then concrete implementation of validators that have the above signature for example

```
func validateAlphabeticalValue(text: String) -> (Bool, String)? {
    let valid = !text!.isEmpty && text!.rangeOfCharacter(from: CharacterSet.letters.inverted) == nil;

    guard valid else {
        return (false, "Invalid number")
    }

    return nil
}
```

**Comment by Matic1993** [comment]
Hey @k0nserv 

thank you for your suggestion - do you know for any tutorial where I can check your idea?

I will implement your suggestion.

Thank you for your help.

**Comment by k0nserv** [comment]
So the idea is that each instance of `SkyFloatingLabelTextField` will have an optional validator function(`Validator?`). 

```swift
typealias Validator = (_ text: String) -> ValidationResult
```
`ValidationResult` is just a simple enum encapsulating either a validity or an error with a string to describe the error.

```swift
enum ValidationResult {
    case ok
    case error(String)
}
```

Everytime the text changes we can run the Validator if it exists and then set the `errorMessage` as appropriate. We need to make sure we listen to text changes in a transparent way that still lets the consumer set a custom `delegate`. See attached playground 

[Validator.playground.zip](https://github.com/Skyscanner/SkyFloatingLabelTextField/files/1173086/Validator.playground.zip)

**Comment by k0nserv** [comment]
Closing due to inactivity

**Pull request closed without merging**
