### PR TITLE
Swift 3 Support

### PR DESCRIPTION
**Pull request by hyerra**
Hello everyone,
I recently added Swift 3 support and I was thinking that it would be a great additional branch that other users could use if they are using Swift 3. Possibly we could create a brand new Swift 3 branch and have this code be placed in that branch in order to have the main branch running Swift 2.2 code.

### CODE REVIEW

**Comment by hyerra** [comment]
Also, I wanted to mention it does fail the travis-ci check but that is because I'm using Swift 3.

**Comment by mirzadelic** [comment]
+1

**Comment by hyerra** [comment]
Yeah, we really need Swift 3 support for the library.

**Comment by hyerra** [comment]
Good point! I didn't realize that because my deployment target was set to iOS 8. Thanks for bringing the issue up.

**Comment by wolffan** [comment]
@hyerra Thanks for your time on this.
I'll use the above PR for swift that has all checks green. During the day I'll do the review + merge

**Pull request closed without merging**
