### PR TITLE
Added titleFont var to set another font in title label

### PR DESCRIPTION
**Pull request by rubenadlm**

### CODE REVIEW

**Comment by k0nserv** [comment]
Looks good @rubenadlm can you add an entry to `CHANGELOG.md` under the master section crediting yourself and explaining the change?

**Comment by rubenadlm** [comment]
Done, thanks @k0nserv

**Comment by bogren** [comment]
Thanks for the contribution. LGTM! 👍

**Comment by k0nserv** [comment]
Thanks a bunch for your contribution 😄

**Pull request merged**
