### PR TITLE
Update code style to common Swift style

### PR DESCRIPTION
**Pull request by moogle19**
Hi,
I updated some of the variable declarations with spaces after the colons and also omitted `self`'s where possible (as recommended).

### CODE REVIEW

**Comment by k0nserv** [comment]
This is great 👍 I've been thinking about swiftlint recently and this looks like a good step in that direction. Feel free to add it to the project if you feel inclined, otherwise I'll do it on the back of your work.

**Comment by k0nserv** [comment]
Also please credit yourself in `CHANGELOG.md` under the `master` section

**Comment by moogle19** [comment]
@k0nserv 
I added `swiftlint` as a Build Phase (not sure if should run automatically on build or manually?) and fixed the errors and warnings generated by `swiftlint`.

I used the default `swiftlint` settings (not sure if something specific should be enabled/disabled).

To fix the line length warnings (120 characters) I used this style of indentation.
```
addErrorButton?.setTitle(NSLocalizedString("Add error",
                                           tableName: "SkyFloatingLabelTextField",
                                           comment: "add error button title"), for: .normal)
```
I hope this is okay or is there a preferable style?

Let me know when something is wrong or needs change.

(There also was a commit I did not intend to push which I reverted afterwards)

**Comment by k0nserv** [comment]
I think I prefer the style

```
addErrorButton?.setTitle(
    NSLocalizedString("Add error",
    tableName: "SkyFloatingLabelTextField",
    comment: "add error button title"), for: .normal
)
```

@bogren opinions?

**Comment by bogren** [comment]
👍 
```addErrorButton?.setTitle(
    NSLocalizedString("Add error",
    tableName: "SkyFloatingLabelTextField",
    comment: "add error button title"), 
    for: .normal
)```

**Comment by bogren** [comment]
Or like this? 😃  
```
addErrorButton?.setTitle(NSLocalizedString("Add error",
                                           tableName: "SkyFloatingLabelTextField",
                                           comment: "add error button title"),
                         for: .normal
)
```

**Comment by k0nserv** [comment]
This is how I would write it
```
addErrorButton?.setTitle(
    NSLocalizedString(
        "Add error",
        tableName: "SkyFloatingLabelTextField",
        comment: "add error button title"
    ),
    for: .normal
)
```

**Comment by k0nserv** [comment]
Thanks a bunch for the PR @moogle19

**Pull request merged**
