### PR TITLE
- example project view controller class simplified

### PR DESCRIPTION
**Pull request by slxl**

### CODE REVIEW

**Comment by k0nserv** [comment]
Hey @slxl this looks good. We are merging #67 into master soon so it'll probably have to be updated to Swift 3 after that point

**Comment by k0nserv** [comment]
@slxl #67 is merged now if you wanna rebase this

**Comment by slxl** [comment]
pardonne moi delay :)

**Comment by k0nserv** [comment]
No problem the same on my part :)

**Pull request merged**
